<a href="https://colab.research.google.com/github/syhennie/data-quality-process/blob/main/features.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Настройка окружения

In [1]:
%pip install numpy gensim pandas scipy sdv matplotlib graphviz faker

Requirement already satisfied: numpy in c:\users\stepa\appdata\local\programs\python\python311\lib\site-packages (2.3.5)
Requirement already satisfied: gensim in c:\users\stepa\appdata\local\programs\python\python311\lib\site-packages (4.4.0)
Requirement already satisfied: pandas in c:\users\stepa\appdata\local\programs\python\python311\lib\site-packages (2.3.3)
Requirement already satisfied: scipy in c:\users\stepa\appdata\local\programs\python\python311\lib\site-packages (1.16.3)
Requirement already satisfied: sdv in c:\users\stepa\appdata\local\programs\python\python311\lib\site-packages (1.29.1)
Requirement already satisfied: matplotlib in c:\users\stepa\appdata\local\programs\python\python311\lib\site-packages (3.10.7)
Requirement already satisfied: graphviz in c:\users\stepa\appdata\local\programs\python\python311\lib\site-packages (0.21)
Requirement already satisfied: faker in c:\users\stepa\appdata\local\programs\python\python311\lib\site-packages (38.2.0)
Requirement already satisfied: smart_open>=1.8.1 in c:\users\stepa\appdata\local\programs\python\python311\lib\site-packages (from gensim) (7.5.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\stepa\appdata\roaming\python\python311\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\stepa\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\stepa\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: boto3<2.0.0,>=1.28 in c:\users\stepa\appdata\local\programs\python\python311\lib\site-packages (from sdv) (1.42.0)
Requirement already satisfied: botocore<2.0.0,>=1.31 in c:\users\stepa\appdata\local\programs\python\python311\lib\site-packages (from sdv) (1.41.6)
Requirement already satisfied: cloudpickle>=2.1.0 in c:\users\stepa\appdata\local\programs\python\python311\lib\site-packages (from sdv) (3.1.2)
Requirement already satisfied: tqdm>=4.29 in c:\users\stepa\appdata\local\programs\python\python311\lib\site-packages (from sdv) (4.67.1)
Requirement already satisfied: copulas>=0.12.1 in c:\users\stepa\appdata\local\programs\python\python311\lib\site-packages (from sdv) (0.12.3)
Requirement already satisfied: ctgan>=0.11.0 in c:\users\stepa\appdata\local\programs\python\python311\lib\site-packages (from sdv) (0.11.1)
Requirement already satisfied: deepecho>=0.7.0 in c:\users\stepa\appdata\local\programs\python\python311\lib\site-packages (from sdv) (0.7.0)
Requirement already satisfied: rdt>=1.18.2 in c:\users\stepa\appdata\local\programs\python\python311\lib\site-packages (from sdv) (1.18.2)
Requirement already satisfied: sdmetrics>=0.21.0 in c:\users\stepa\appdata\local\programs\python\python311\lib\site-packages (from sdv) (0.24.0)
Requirement already satisfied: platformdirs>=4.0 in c:\users\stepa\appdata\roaming\python\python311\site-packages (from sdv) (4.5.0)
Requirement already satisfied: pyyaml>=6.0.1 in c:\users\stepa\appdata\local\programs\python\python311\lib\site-packages (from sdv) (6.0.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\stepa\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\stepa\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\stepa\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (4.61.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\stepa\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\stepa\appdata\roaming\python\python311\site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\stepa\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (12.0.0)
Requirement already satisfied: pyparsing>=3 in c:\users\stepa\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (3.2.5)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in c:\users\stepa\appdata\local\programs\python\python311\lib\site-packages (from boto3<2.0.0,>=1.28->sdv) (1.0.1)
Requirement already satisfied: s3transfer<0.17.0,>=0.16.0 in c:\users\stepa\appdata\local\programs\python\python311\lib\site-packages (from boto3<2.0.0,>=1.28->sdv) (0.16.0)
Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in c:\users\stepa\appdata\local\programs\python\python311\lib\site-packages (from botocore<2.0.0,>=1.31->sdv) (2.5.0)
Requirement already satisfied: plotly>=5.10.0 in c:\users\stepa\appdata\local\programs\python\python311\lib\site-packages (from copulas>=0.12.1->sdv) (6.5.0)
Requirement already satisfied: torch>=2.0.0 in c:\users\stepa\appdata\local\programs\python\python311\lib\site-packages (from ctgan>=0.11.0->sdv) (2.9.0+cu130)
Requirement already satisfied: six>=1.5 in c:\users\stepa\appdata\roaming\python\python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: scikit-learn>=1.1.3 in c:\users\stepa\appdata\local\programs\python\python311\lib\site-packages (from rdt>=1.18.2->sdv) (1.7.2)
Requirement already satisfied: wrapt in c:\users\stepa\appdata\local\programs\python\python311\lib\site-packages (from smart_open>=1.8.1->gensim) (2.0.1)
Requirement already satisfied: colorama in c:\users\stepa\appdata\roaming\python\python311\site-packages (from tqdm>=4.29->sdv) (0.4.6)
Requirement already satisfied: narwhals>=1.15.1 in c:\users\stepa\appdata\local\programs\python\python311\lib\site-packages (from plotly>=5.10.0->copulas>=0.12.1->sdv) (2.13.0)
Requirement already satisfied: joblib>=1.2.0 in c:\users\stepa\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn>=1.1.3->rdt>=1.18.2->sdv) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\stepa\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn>=1.1.3->rdt>=1.18.2->sdv) (3.6.0)
Requirement already satisfied: filelock in c:\users\stepa\appdata\local\programs\python\python311\lib\site-packages (from torch>=2.0.0->ctgan>=0.11.0->sdv) (3.20.0)
Requirement already satisfied: typing-extensions>=4.10.0 in c:\users\stepa\appdata\roaming\python\python311\site-packages (from torch>=2.0.0->ctgan>=0.11.0->sdv) (4.15.0)
Requirement already satisfied: sympy>=1.13.3 in c:\users\stepa\appdata\local\programs\python\python311\lib\site-packages (from torch>=2.0.0->ctgan>=0.11.0->sdv) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in c:\users\stepa\appdata\local\programs\python\python311\lib\site-packages (from torch>=2.0.0->ctgan>=0.11.0->sdv) (3.6)
Requirement already satisfied: jinja2 in c:\users\stepa\appdata\local\programs\python\python311\lib\site-packages (from torch>=2.0.0->ctgan>=0.11.0->sdv) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in c:\users\stepa\appdata\local\programs\python\python311\lib\site-packages (from torch>=2.0.0->ctgan>=0.11.0->sdv) (2025.10.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\stepa\appdata\local\programs\python\python311\lib\site-packages (from sympy>=1.13.3->torch>=2.0.0->ctgan>=0.11.0->sdv) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\stepa\appdata\local\programs\python\python311\lib\site-packages (from jinja2->torch>=2.0.0->ctgan>=0.11.0->sdv) (3.0.3)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import sys
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy import stats
import sdv
import pathlib

In [3]:
df = pd.read_csv(pathlib.Path('../test.csv'))
df = df.iloc[:, 1:]
df.head()

,article,highlights
0,Ever noticed how plane seats appear to be gett...,Experts question if packed out planes are put...
1,A drunk teenage boy had to be rescued by secur...,Drunk teenage boy climbed into lion enclosure ...
2,Dougie Freedman is on the verge of agreeing a ...,Nottingham Forest are close to extending Dougi...
3,Liverpool target Neto is also wanted by PSG an...,Fiorentina goalkeeper Neto has been linked wit...
4,Bruce Jenner will break his silence in a two-h...,"Tell-all interview with the reality TV star, 6..."

In [4]:
from gensim.models import Word2Vec, FastText
from gensim.utils import simple_preprocess

model = FastText.load("../fasttext_lee_background")

MAX_TOKENS_PER_ENTRY = 10
VECTOR_SIZE = 64

def vectorise_entries(entries):
    features = []
    for entry in entries:
        tokens = simple_preprocess(entry)
        vectors = [model.wv[token] for token in tokens]
        length = min(len(vectors), MAX_TOKENS_PER_ENTRY)
        trimmed_vectors = vectors[:length]
        if length < MAX_TOKENS_PER_ENTRY:
            padding_vectors = [np.zeros(VECTOR_SIZE) for _ in range(MAX_TOKENS_PER_ENTRY - length)]
            trimmed_vectors += padding_vectors
        features.append(np.concatenate(trimmed_vectors))
    return np.array(features)

In [5]:
def decode_row(row):
    entry = ""
    for i in range(MAX_TOKENS_PER_ENTRY):
        vectorised_token = row[i * VECTOR_SIZE:(i + 1) * VECTOR_SIZE]
        most_similar_words = model.wv.similar_by_vector(vectorised_token, topn=5)
        for word, _ in most_similar_words:
            if str(word).isalnum():
                entry += f" {word}"
    return entry

In [6]:
import torch
print(torch.cuda.is_available())
num_gpus = torch.cuda.device_count()
for i in range(num_gpus):
    print(f"Device {i}: {torch.cuda.get_device_name(i)}")
torch.cuda.set_device(0)

True
Device 0: NVIDIA GeForce RTX 5070 Ti

In [7]:
from sdv.metadata import Metadata
from sdv.single_table import CTGANSynthesizer, TVAESynthesizer


df_sample = df.sample(1000)
df_result = pd.DataFrame()

for column in df_sample.columns:
    entries = [x for x in df_sample[column]]
    vectorised_entries = vectorise_entries(entries)

    column_df = pd.DataFrame(vectorised_entries)
    metadata = Metadata.detect_from_dataframe(column_df)
    synthesizer = CTGANSynthesizer(metadata)
    synthesizer.fit(column_df)

    synthetic_data = synthesizer.sample(num_rows=1000).values
    result = np.apply_along_axis(decode_row, 1, synthetic_data)
    df_result[column] = result

df_result

c:\Users\stepa\AppData\Local\Programs\Python\Python311\Lib\site-packages\sdv\single_table\base.py:134: UserWarning: We strongly recommend saving the metadata using 'save_to_json' for replicability in future SDV versions.
  warnings.warn(

PerformanceAlert: Using the CTGANSynthesizer on this data is not recommended. To model this data, CTGAN will generate a large number of columns.

Original Column Name   Est # of Columns (CTGAN)
0                      11
1                      11
2                      11
3                      11
4                      11
5                      11
6                      11
7                      11
8                      11
9                      11
10                     11
11                     11
12                     11
13                     11
14                     11
15                     11
16                     11
17                     11
18                     11
19                     11
20                     11
21                     11
22                     11
23                     11
24                     11
25                     11
26                     11
27                     11
28                     11
29                     11
30                     11
31                     11
32                     11
33                     11
34                     11
35                     11
36                     11
37                     11
38                     11
39                     11
40                     11
41                     11
42                     11
43                     11
44                     11
45                     11
46                     11
47                     11
48                     11
49                     11
50                     11
51                     11
52                     11
53                     11
54                     11
55                     11
56                     11
57                     11
58                     11
59                     11
60                     11
61                     11
62                     11
63                     11
64                     11
65                     11
66                     11
67                     11
68                     11
69                     11
70                     11
71                     11
72                     11
73                     11
74                     11
75                     11
76                     11
77                     11
78                     11
79                     11
80                     11
81                     11
82                     11
83                     11
84                     11
85                     11
86                     11
87                     11
88                     11
89                     11
90                     11
91                     11
92                     11
93                     11
94                     11
95                     11
96                     11
97                     11
98                     11
99                     11
100                    11
101                    11
102                    11
103                    11
104                    11
105                    11
106                    11
107                    11
108                    11
109                    11
110                    11
111                    11
112                    11
113                    11
114                    11
115                    11
116                    11
117                    11
118                    11
119                    11
120                    11
121                    11
122                    11
123                    11
124                    11
125                    11
126                    11
127                    11
128                    11
129                    11
130                    11
131                    11
132                    11
133                    11
134                    11
135                    11
136                    11
137                    11
138                    11
139                    11
140                    11
141                    11
142                    11
143                    11
144                    11
145                    11
146                    11
147                    11
148                    11
149                    11
150                    11
151                    11
152                    11
153                    11
154                    11
155                    11
156                    11
157                    11
158                    11
159                    11
160                    11
161                    11
162                    11
163                    11
164                    11
165                    11
166                    11
167                    11
168                    11
169                    11
170                    11
171                    11
172                    11
173                    11
174                    11
175                    11
176                    11
177                    11
178                    11
179                    11
180                    11
181                    11
182                    11
183                    11
184                    11
185                    11
186                    11
187                    11
188                    11
189                    11
190                    11
191                    11
192                    11
193                    11
194                    11
195                    11
196                    11
197                    11
198                    11
199                    11
200                    11
201                    11
202                    11
203                    11
204                    11
205                    11
206                    11
207                    11
208                    11
209                    11
210                    11
211                    11
212                    11
213                    11
214                    11
215                    11
216                    11
217                    11
218                    11
219                    11
220                    11
221                    11
222                    11
223                    11
224                    11
225                    11
226                    11
227                    11
228                    11
229                    11
230                    11
231                    11
232                    11
233                    11
234                    11
235                    11
236                    11
237                    11
238                    11
239                    11
240                    11
241                    11
242                    11
243                    11
244                    11
245                    11
246                    11
247                    11
248                    11
249                    11
250                    11
251                    11
252                    11
253                    11
254                    11
255                    11
256                    11
257                    11
258                    11
259                    11
260                    11
261                    11
262                    11
263                    11
264                    11
265                    11
266                    11
267                    11
268                    11
269                    11
270                    11
271                    11
272                    11
273                    11
274                    11
275                    11
276                    11
277                    11
278                    11
279                    11
280                    11
281                    11
282                    11
283                    11
284                    11
285                    11
286                    11
287                    11
288                    11
289                    11
290                    11
291                    11
292                    11
293                    11
294                    11
295                    11
296                    11
297                    11
298                    11
299                    11
300                    11
301                    11
302                    11
303                    11
304                    11
305                    11
306                    11
307                    11
308                    11
309                    11
310                    11
311                    11
312                    11
313                    11
314                    11
315                    11
316                    11
317                    11
318                    11
319                    11
320                    11
321                    11
322                    11
323                    11
324                    11
325                    11
326                    11
327                    11
328                    11
329                    11
330                    11
331                    11
332                    11
333                    11
334                    11
335                    11
336                    11
337                    11
338                    11
339                    11
340                    11
341                    11
342                    11
343                    11
344                    11
345                    11
346                    11
347                    11
348                    11
349                    11
350                    11
351                    11
352                    11
353                    11
354                    11
355                    11
356                    11
357                    11
358                    11
359                    11
360                    11
361                    11
362                    11
363                    11
364                    11
365                    11
366                    11
367                    11
368                    11
369                    11
370                    11
371                    11
372                    11
373                    11
374                    11
375                    11
376                    11
377                    11
378                    11
379                    11
380                    11
381                    11
382                    11
383                    11
384                    11
385                    11
386                    11
387                    11
388                    11
389                    11
390                    11
391                    11
392                    11
393                    11
394                    11
395                    11
396                    11
397                    11
398                    11
399                    11
400                    11
401                    11
402                    11
403                    11
404                    11
405                    11
406                    11
407                    11
408                    11
409                    11
410                    11
411                    11
412                    11
413                    11
414                    11
415                    11
416                    11
417                    11
418                    11
419                    11
420                    11
421                    11
422                    11
423                    11
424                    11
425                    11
426                    11
427                    11
428                    11
429                    11
430                    11
431                    11
432                    11
433                    11
434                    11
435                    11
436                    11
437                    11
438                    11
439                    11
440                    11
441                    11
442                    11
443                    11
444                    11
445                    11
446                    11
447                    11
448                    11
449                    11
450                    11
451                    11
452                    11
453                    11
454                    11
455                    11
456                    11
457                    11
458                    11
459                    11
460                    11
461                    11
462                    11
463                    11
464                    11
465                    11
466                    11
467                    11
468                    11
469                    11
470                    11
471                    11
472                    11
473                    11
474                    11
475                    11
476                    11
477                    11
478                    11
479                    11
480                    11
481                    11
482                    11
483                    11
484                    11
485                    11
486                    11
487                    11
488                    11
489                    11
490                    11
491                    11
492                    11
493                    11
494                    11
495                    11
496                    11
497                    11
498                    11
499                    11
500                    11
501                    11
502                    11
503                    11
504                    11
505                    11
506                    11
507                    11
508                    11
509                    11
510                    11
511                    11
512                    11
513                    11
514                    11
515                    11
516                    11
517                    11
518                    11
519                    11
520                    11
521                    11
522                    11
523                    11
524                    11
525                    11
526                    11
527                    11
528                    11
529                    11
530                    11
531                    11
532                    11
533                    11
534                    11
535                    11
536                    11
537                    11
538                    11
539                    11
540                    11
541                    11
542                    11
543                    11
544                    11
545                    11
546                    11
547                    11
548                    11
549                    11
550                    11
551                    11
552                    11
553                    11
554                    11
555                    11
556                    11
557                    11
558                    11
559                    11
560                    11
561                    11
562                    11
563                    11
564                    11
565                    11
566                    11
567                    11
568                    11
569                    11
570                    11
571                    11
572                    11
573                    11
574                    11
575                    11
576                    11
577                    11
578                    11
579                    11
580                    11
581                    11
582                    11
583                    11
584                    11
585                    11
586                    11
587                    11
588                    11
589                    11
590                    11
591                    11
592                    11
593                    11
594                    11
595                    11
596                    11
597                    11
598                    11
599                    11
600                    11
601                    11
602                    11
603                    11
604                    11
605                    11
606                    11
607                    11
608                    11
609                    11
610                    11
611                    11
612                    11
613                    11
614                    11
615                    11
616                    11
617                    11
618                    11
619                    11
620                    11
621                    11
622                    11
623                    11
624                    11
625                    11
626                    11
627                    11
628                    11
629                    11
630                    11
631                    11
632                    11
633                    11
634                    11
635                    11
636                    11
637                    11
638                    11
639                    11

We recommend preprocessing discrete columns that can have many values, using 'update_transformers'. Or you may drop columns that are not necessary to model. (Exit this script using ctrl-C)

c:\Users\stepa\AppData\Local\Programs\Python\Python311\Lib\site-packages\ctgan\synthesizers\_utils.py:16: FutureWarning: `cuda` parameter is deprecated and will be removed in a future release. Please use `enable_gpu` instead.
  warnings.warn(
c:\Users\stepa\AppData\Local\Programs\Python\Python311\Lib\site-packages\sdv\single_table\base.py:134: UserWarning: We strongly recommend saving the metadata using 'save_to_json' for replicability in future SDV versions.
  warnings.warn(

PerformanceAlert: Using the CTGANSynthesizer on this data is not recommended. To model this data, CTGAN will generate a large number of columns.

Original Column Name   Est # of Columns (CTGAN)
0                      11
1                      11
2                      11
3                      11
4                      11
5                      11
6                      11
7                      11
8                      11
9                      11
10                     11
11                     11
12                     11
13                     11
14                     11
15                     11
16                     11
17                     11
18                     11
19                     11
20                     11
21                     11
22                     11
23                     11
24                     11
25                     11
26                     11
27                     11
28                     11
29                     11
30                     11
31                     11
32                     11
33                     11
34                     11
35                     11
36                     11
37                     11
38                     11
39                     11
40                     11
41                     11
42                     11
43                     11
44                     11
45                     11
46                     11
47                     11
48                     11
49                     11
50                     11
51                     11
52                     11
53                     11
54                     11
55                     11
56                     11
57                     11
58                     11
59                     11
60                     11
61                     11
62                     11
63                     11
64                     11
65                     11
66                     11
67                     11
68                     11
69                     11
70                     11
71                     11
72                     11
73                     11
74                     11
75                     11
76                     11
77                     11
78                     11
79                     11
80                     11
81                     11
82                     11
83                     11
84                     11
85                     11
86                     11
87                     11
88                     11
89                     11
90                     11
91                     11
92                     11
93                     11
94                     11
95                     11
96                     11
97                     11
98                     11
99                     11
100                    11
101                    11
102                    11
103                    11
104                    11
105                    11
106                    11
107                    11
108                    11
109                    11
110                    11
111                    11
112                    11
113                    11
114                    11
115                    11
116                    11
117                    11
118                    11
119                    11
120                    11
121                    11
122                    11
123                    11
124                    11
125                    11
126                    11
127                    11
128                    11
129                    11
130                    11
131                    11
132                    11
133                    11
134                    11
135                    11
136                    11
137                    11
138                    11
139                    11
140                    11
141                    11
142                    11
143                    11
144                    11
145                    11
146                    11
147                    11
148                    11
149                    11
150                    11
151                    11
152                    11
153                    11
154                    11
155                    11
156                    11
157                    11
158                    11
159                    11
160                    11
161                    11
162                    11
163                    11
164                    11
165                    11
166                    11
167                    11
168                    11
169                    11
170                    11
171                    11
172                    11
173                    11
174                    11
175                    11
176                    11
177                    11
178                    11
179                    11
180                    11
181                    11
182                    11
183                    11
184                    11
185                    11
186                    11
187                    11
188                    11
189                    11
190                    11
191                    11
192                    11
193                    11
194                    11
195                    11
196                    11
197                    11
198                    11
199                    11
200                    11
201                    11
202                    11
203                    11
204                    11
205                    11
206                    11
207                    11
208                    11
209                    11
210                    11
211                    11
212                    11
213                    11
214                    11
215                    11
216                    11
217                    11
218                    11
219                    11
220                    11
221                    11
222                    11
223                    11
224                    11
225                    11
226                    11
227                    11
228                    11
229                    11
230                    11
231                    11
232                    11
233                    11
234                    11
235                    11
236                    11
237                    11
238                    11
239                    11
240                    11
241                    11
242                    11
243                    11
244                    11
245                    11
246                    11
247                    11
248                    11
249                    11
250                    11
251                    11
252                    11
253                    11
254                    11
255                    11
256                    11
257                    11
258                    11
259                    11
260                    11
261                    11
262                    11
263                    11
264                    11
265                    11
266                    11
267                    11
268                    11
269                    11
270                    11
271                    11
272                    11
273                    11
274                    11
275                    11
276                    11
277                    11
278                    11
279                    11
280                    11
281                    11
282                    11
283                    11
284                    11
285                    11
286                    11
287                    11
288                    11
289                    11
290                    11
291                    11
292                    11
293                    11
294                    11
295                    11
296                    11
297                    11
298                    11
299                    11
300                    11
301                    11
302                    11
303                    11
304                    11
305                    11
306                    11
307                    11
308                    11
309                    11
310                    11
311                    11
312                    11
313                    11
314                    11
315                    11
316                    11
317                    11
318                    11
319                    11
320                    11
321                    11
322                    11
323                    11
324                    11
325                    11
326                    11
327                    11
328                    11
329                    11
330                    11
331                    11
332                    11
333                    11
334                    11
335                    11
336                    11
337                    11
338                    11
339                    11
340                    11
341                    11
342                    11
343                    11
344                    11
345                    11
346                    11
347                    11
348                    11
349                    11
350                    11
351                    11
352                    11
353                    11
354                    11
355                    11
356                    11
357                    11
358                    11
359                    11
360                    11
361                    11
362                    11
363                    11
364                    11
365                    11
366                    11
367                    11
368                    11
369                    11
370                    11
371                    11
372                    11
373                    11
374                    11
375                    11
376                    11
377                    11
378                    11
379                    11
380                    11
381                    11
382                    11
383                    11
384                    11
385                    11
386                    11
387                    11
388                    11
389                    11
390                    11
391                    11
392                    11
393                    11
394                    11
395                    11
396                    11
397                    11
398                    11
399                    11
400                    11
401                    11
402                    11
403                    11
404                    11
405                    11
406                    11
407                    11
408                    11
409                    11
410                    11
411                    11
412                    11
413                    11
414                    11
415                    11
416                    11
417                    11
418                    11
419                    11
420                    11
421                    11
422                    11
423                    11
424                    11
425                    11
426                    11
427                    11
428                    11
429                    11
430                    11
431                    11
432                    11
433                    11
434                    11
435                    11
436                    11
437                    11
438                    11
439                    11
440                    11
441                    11
442                    11
443                    11
444                    11
445                    11
446                    11
447                    11
448                    11
449                    11
450                    11
451                    11
452                    11
453                    11
454                    11
455                    11
456                    11
457                    11
458                    11
459                    11
460                    11
461                    11
462                    11
463                    11
464                    11
465                    11
466                    11
467                    11
468                    11
469                    11
470                    11
471                    11
472                    11
473                    11
474                    11
475                    11
476                    11
477                    11
478                    11
479                    11
480                    11
481                    11
482                    11
483                    11
484                    11
485                    11
486                    11
487                    11
488                    11
489                    11
490                    11
491                    11
492                    11
493                    11
494                    11
495                    11
496                    11
497                    11
498                    11
499                    11
500                    11
501                    11
502                    11
503                    11
504                    11
505                    11
506                    11
507                    11
508                    11
509                    11
510                    11
511                    11
512                    11
513                    11
514                    11
515                    11
516                    11
517                    11
518                    11
519                    11
520                    11
521                    11
522                    11
523                    11
524                    11
525                    11
526                    11
527                    11
528                    11
529                    11
530                    11
531                    11
532                    11
533                    11
534                    11
535                    11
536                    11
537                    11
538                    11
539                    11
540                    11
541                    11
542                    11
543                    11
544                    11
545                    11
546                    11
547                    11
548                    11
549                    11
550                    11
551                    11
552                    11
553                    11
554                    11
555                    11
556                    11
557                    11
558                    11
559                    11
560                    11
561                    11
562                    11
563                    11
564                    11
565                    11
566                    11
567                    11
568                    11
569                    11
570                    11
571                    11
572                    11
573                    11
574                    11
575                    11
576                    11
577                    11
578                    11
579                    11
580                    11
581                    11
582                    11
583                    11
584                    11
585                    11
586                    11
587                    11
588                    11
589                    11
590                    11
591                    11
592                    11
593                    11
594                    11
595                    11
596                    11
597                    11
598                    11
599                    11
600                    11
601                    11
602                    11
603                    11
604                    11
605                    11
606                    11
607                    11
608                    11
609                    11
610                    11
611                    11
612                    11
613                    11
614                    11
615                    11
616                    11
617                    11
618                    11
619                    11
620                    11
621                    11
622                    11
623                    11
624                    11
625                    11
626                    11
627                    11
628                    11
629                    11
630                    11
631                    11
632                    11
633                    11
634                    11
635                    11
636                    11
637                    11
638                    11
639                    11

We recommend preprocessing discrete columns that can have many values, using 'update_transformers'. Or you may drop columns that are not necessary to model. (Exit this script using ctrl-C)

c:\Users\stepa\AppData\Local\Programs\Python\Python311\Lib\site-packages\ctgan\synthesizers\_utils.py:16: FutureWarning: `cuda` parameter is deprecated and will be removed in a future release. Please use `enable_gpu` instead.
  warnings.warn(

,article,highlights
0,24 48 26 80 AFP ANZ HIV 1 25 blaze drug am Zi...,23 80 At W 24 AFP Up 15 SES HIV drug W 25 40 ...
1,25 150 my If Fatah 26 24 48 If Up 2 On UN 150...,Mt 13 21 12 150 1 26 14 drug Assa 15 Up 12 HI...
2,blaze 21 Sarah gun Nauru 11 25 Up No 48 No UN...,24 SES ANZ embassy W 13 25 18 Ms As 40 15 14 ...
3,80 21 On If Nauru 150 Fatah Doug If 48 Mt AFP...,11 20 Fatah Road 12 As drug Assa 5 SES Mt Up ...
4,AFP Up She keep His Up As 2 W 25 Up 1 Nauru 2...,80 24 18 2 HIH AFP 14 W 26 Bonn Blue my 150 S...
...,...,...
995,On No HIV 11 W UN W No At 11 23 500 400 Europ...,HIV Fatah drug oil Two 5 80 40 HIV drug 80 26...
996,26 48 Nauru Bonn school Up HIV 48 24 ANZ Up M...,26 1 W ANZ At 14 Lee ANZ Africa 48 15 150 Dr ...
997,gun 23 40 24 She 24 W 40 blaze At 23 News 14 ...,Up 14 12 1 23 Bonn Nauru 14 18 14 Kabul 12 Tw...
998,If 150 various boy HIV SES 24 W Ms Hewitt 20 ...,13 15 HIV 14 26 Up 25 As 150 23 21 500 13 Mt ...
999,80 1 blaze Sir 20 25 80 AFP W drug drug am my...,15 25 ANZ 24 1 Up 26 Nauru HIV 48 SES Sarah o...

In [8]:
def get_vectorised_entries(entries):
    features = []
    for entry in entries:
        tokens = simple_preprocess(entry, min_len=1)
        vectors = [model.wv[token] for token in tokens]
        features.append(np.mean(vectors, axis=0))
    return np.array(features)

In [12]:
summary_stats = []
features_data = []

for column in df.columns:
    entries = [x for x in df[column]]
    features = get_vectorised_entries(entries)
    vectorised_entries = vectorise_entries(entries)

    # Features-based metrics
    #
    # mean = np.mean(features, axis=0)
    # standard_deviation = np.std(features, axis=0)
    # median = np.median(features, axis=0)
    # asymmetry = stats.skew(features, axis=0)
    # excess = stats.kurtosis(features, axis=0)

    mean = np.mean(vectorised_entries, axis=0)
    standard_deviation = np.std(vectorised_entries, axis=0)
    median = np.median(vectorised_entries, axis=0)
    asymmetry = stats.skew(vectorised_entries, axis=0)
    excess = stats.kurtosis(vectorised_entries, axis=0)

    summary_stats.append({
        'column': column,
        'overall_mean': np.mean(mean),
        'overall_std': np.mean(standard_deviation),
        'std_of_means': np.std(mean),
        'mean_of_medians': np.mean(median),
        'asymmetry_avg': np.mean(asymmetry),
        'excess_avg': np.mean(excess),
        'n_entries': len(entries),
        'vector_dim': vectorised_entries.shape[1]
    })

    features_data.append({
            'column': column,
            'vectors': features
        })

summary_df = pd.DataFrame(summary_stats)
summary_df

,column,overall_mean,overall_std,std_of_means,mean_of_medians,asymmetry_avg,excess_avg,n_entries,vector_dim
0,article,-0.033408,0.189726,0.417737,-0.031447,-0.064652,-0.125835,11490,640
1,highlights,-0.032024,0.195210,0.403500,-0.028976,-0.088079,0.203277,11490,640

In [13]:
def validate_synthetic_data(original_stats, synthetic_data):
    validation_results = []

    for column in synthetic_data.columns:
        column_stats = original_stats[original_stats['column'] == column]
        entries = [x for x in synthetic_data[column]]
        features = get_vectorised_entries(entries)

        synth_mean = np.mean(features, axis=0)
        synth_std = np.std(features, axis=0)
        synth_skew = stats.skew(features, axis=0)
        synth_kurt = stats.kurtosis(features, axis=0)

        validation_results.append({
            'column': column_stats['column'].tolist()[0],
            'original_mean': column_stats['overall_mean'].tolist()[0],
            'synthetic_mean': np.mean(synth_mean),
            'mean_error': np.abs(np.mean(synth_mean) - column_stats['overall_mean'].tolist()[0]),

            'original_std': column_stats['overall_std'].tolist()[0],
            'synthetic_std': np.mean(synth_std),
            'std_error': np.abs(np.mean(synth_std) - column_stats['overall_std'].tolist()[0]),

            'original_skew': column_stats['asymmetry_avg'].tolist()[0],
            'synthetic_skew': np.mean(synth_skew),
            'skew_error': np.abs(np.mean(synth_skew) - column_stats['asymmetry_avg'].tolist()[0]),

            'original_kurt': column_stats['excess_avg'].tolist()[0],
            'synthetic_kurt': np.mean(synth_kurt),
            'kurt_error': np.abs(np.mean(synth_kurt) - column_stats['excess_avg'].tolist()[0]),

            'n_samples': len(features),
            'vector_dim': features.shape[1]
        })

    return pd.DataFrame(validation_results)

In [15]:
validation_df = validate_synthetic_data(summary_df, df_result)

# validation_df[['column', 'mean_error', 'std_error', 'skew_error', 'kurt_error']]
validation_df[['column', 'original_mean', 'synthetic_mean', 'mean_error', 'original_std', 'synthetic_std', 'std_error', 'original_skew', 'synthetic_skew', 'skew_error', 'original_kurt', 'synthetic_kurt', 'kurt_error']]
# print(validation_df[['column', 'mean_error', 'std_error', 'skew_error', 'kurt_error']])

,column,original_mean,synthetic_mean,mean_error,original_std,synthetic_std,std_error,original_skew,synthetic_skew,skew_error,original_kurt,synthetic_kurt,kurt_error
0,article,-0.033408,-0.019497,0.013911,0.189726,0.038916,0.150809,-0.064652,-0.013004,0.051648,-0.125835,0.053503,0.179337
1,highlights,-0.032024,-0.017962,0.014061,0.195210,0.038512,0.156698,-0.088079,-0.024766,0.063313,0.203277,-0.172453,0.375730